services:
# PostgreSQL database service
  postgres:
    container_name: postgres_demo
    image: postgres:latest
    env_file:
      - .env
    volumes:
       - postgres-db:/data/postgres
       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "psql -U ${POSTGRES_USER} -q -d ${POSTGRES_DB} -c \"SELECT 'ready';\""]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 5s

# pgAdmin for managing PostgreSQL
  pgadmin: 
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-db:/var/lib/pgadmin
    depends_on:
      - postgres
      
volumes:
  postgres-db:
    driver: local
  pgadmin-db:
    driver: local

  